"use client";

import React, { useEffect, useState } from "react";
import { CheckCircle2, XCircle, AlertCircle } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { fetchFromMetaphor } from "@/app/api";

type PendingNode = {
  id: string;
  title: string;
  type: string;
  summary: string;
  content: string;
  confidence: number;
  created_at: string;
};

export default function InboxPage() {
  const [nodes, setNodes] = useState<PendingNode[]>([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  useEffect(() => {
    fetchInbox();
  }, []);

  const fetchInbox = async () => {
    setLoading(true);
    try {
      const data = await fetchFromMetaphor("/graph/inbox");
      if (data && data.nodes) {
        setNodes(data.nodes);
      }
    } catch (e) {
      console.error("Failed to fetch inbox:", e);
    }
    setLoading(false);
  };

  const handleAction = async (nodeId: string, action: "approve" | "reject") => {
    setActionLoading(nodeId);
    try {
      await fetchFromMetaphor(`/graph/nodes/${nodeId}/${action}`, { method: "POST" });
      setNodes((prev) => prev.filter((n) => n.id !== nodeId));
    } catch (e) {
      console.error(`Failed to ${action} node:`, e);
    }
    setActionLoading(null);
  };

  return (
    <div className="w-full max-w-5xl mx-auto p-8 animate-fade-in-up">
      <div className="mb-10 w-full border-b border-border-subtle/50 pb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl text-foreground font-medium tracking-tight leading-snug mb-2">Context Inbox</h1>
          <p className="text-muted text-sm font-medium tracking-tight">
            Review and approve pending knowledge graph mutations generated by the Reflection Engine.
          </p>
        </div>
        <div className="flex items-center gap-2 px-4 py-2 bg-surface-1 rounded-full border border-border-subtle">
          <AlertCircle className="w-4 h-4 text-warning" />
          <span className="text-sm font-medium text-foreground">{nodes.length} Pending</span>
        </div>
      </div>

      {loading ? (
        <div className="w-full flex items-center justify-center p-12">
          <div className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : nodes.length === 0 ? (
        <div className="w-full flex flex-col items-center justify-center p-24 bg-surface-1 rounded-2xl border border-border-subtle border-dashed">
          <CheckCircle2 className="w-12 h-12 text-success/50 mb-4" />
          <h2 className="text-lg font-medium text-foreground mb-2">Inbox Zero</h2>
          <p className="text-sm text-muted">All context nodes have been reviewed.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-6">
          {nodes.map((node) => (
            <Card key={node.id} className="p-6 flex flex-col md:flex-row gap-6 justify-between items-start">
              <div className="flex-1 space-y-4">
                <div className="flex items-center gap-3">
                  <span className="px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest rounded-md bg-surface-2 text-foreground border border-border-strong">
                    {node.type}
                  </span>
                  <h3 className="text-lg font-medium text-foreground">{node.title}</h3>
                </div>
                <p className="text-sm text-foreground/80 leading-relaxed bg-surface-1/50 p-4 rounded-xl border border-border-subtle">
                  {node.summary}
                </p>
                <div className="flex items-center gap-4 text-xs font-medium text-muted">
                  <span>Confidence: {(node.confidence * 100).toFixed(0)}%</span>
                  <span>•</span>
                  <span>Created: {new Date(node.created_at).toLocaleString()}</span>
                </div>
              </div>
              
              <div className="flex flex-row md:flex-col gap-3 shrink-0 w-full md:w-auto">
                <button
                  onClick={() => handleAction(node.id, "approve")}
                  disabled={actionLoading === node.id}
                  className="flex-1 md:flex-none flex items-center justify-center gap-2 px-6 py-2.5 rounded-lg bg-foreground text-background text-sm font-medium hover:bg-foreground/90 transition-colors disabled:opacity-50"
                >
                  <CheckCircle2 className="w-4 h-4" />
                  Approve
                </button>
                <button
                  onClick={() => handleAction(node.id, "reject")}
                  disabled={actionLoading === node.id}
                  className="flex-1 md:flex-none flex items-center justify-center gap-2 px-6 py-2.5 rounded-lg bg-surface-2 text-foreground text-sm font-medium border border-border-strong hover:bg-surface-3 transition-colors disabled:opacity-50"
                >
                  <XCircle className="w-4 h-4" />
                  Reject
                </button>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
