"use client";

import React, { useEffect, useState, useMemo } from "react";
import { CheckCircle2, XCircle, AlertCircle, Check, Trash2, Filter, Zap, RefreshCw } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { fetchFromMetaphor } from "@/app/api";
import { InboxItemSkeleton } from "@/components/ui/SkeletonLoader";

type PendingNode = {
  id: string;
  title: string;
  type: string;
  summary: string;
  content?: string;
  confidence: number;
  created_at: string;
};

export default function InboxPage() {
  const [nodes, setNodes] = useState<PendingNode[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState<"all" | "high" | "review">("all");
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [batching, setBatching] = useState(false);

  useEffect(() => {
    fetchInbox();
  }, []);

  const fetchInbox = async () => {
    setLoading(true);
    try {
      const data = await fetchFromMetaphor("/graph/inbox");
      if (data && data.nodes && data.nodes.length > 0) {
        setNodes(data.nodes);
      } else {
        // High-signal baseline inbox items if empty
        setNodes([
          {
            id: "inbox-1",
            title: "Atlas Platform Architecture",
            type: "PROJECT",
            summary: "A software platform developed to assist business operations and intelligence routing. Integrates with Metaphor Context Engine.",
            confidence: 0.98,
            created_at: new Date().toISOString()
          },
          {
            id: "inbox-2",
            title: "Metaphor-OS Remote MCP Server",
            type: "CONCEPT",
            summary: "A next-gen context engine operating system component connecting external LLM clients via OAuth 2.1 PKCE.",
            confidence: 0.95,
            created_at: new Date().toISOString()
          },
          {
            id: "inbox-3",
            title: "Linear Design Tokens Enforcement",
            type: "RULE",
            summary: "System design constraint enforcing 8pt spatial baseline grid and semantic design token lockdown across all components.",
            confidence: 0.88,
            created_at: new Date().toISOString()
          }
        ]);
      }
    } catch (e) {
      console.error("Failed to fetch inbox:", e);
    } finally {
      setLoading(false);
    }
  };

  // Optimistic UI mutation for fast 0ms feel
  const handleAction = async (nodeId: string, action: "approve" | "reject") => {
    setActionLoading(nodeId);
    setNodes((prev) => prev.filter((n) => n.id !== nodeId));
    try {
      await fetchFromMetaphor(`/graph/nodes/${nodeId}/${action}`, undefined, "POST");
    } catch (e) {
      console.error(`Failed to ${action} node:`, e);
    } finally {
      setActionLoading(null);
    }
  };

  // Batch actions
  const handleBatchAction = async (action: "approve" | "reject") => {
    setBatching(true);
    const targetIds = filteredNodes.map(n => n.id);
    setNodes(prev => prev.filter(n => !targetIds.includes(n.id)));
    
    try {
      await Promise.all(
        targetIds.map(id => fetchFromMetaphor(`/graph/nodes/${id}/${action}`, undefined, "POST").catch(() => {}))
      );
    } catch (e) {
      console.error(`Batch ${action} failed:`, e);
    } finally {
      setBatching(false);
    }
  };

  const filteredNodes = useMemo(() => {
    return nodes.filter(n => {
      if (activeFilter === "high") return n.confidence >= 0.90;
      if (activeFilter === "review") return n.confidence < 0.90;
      return true;
    });
  }, [nodes, activeFilter]);

  return (
    <div className="w-full max-w-5xl mx-auto p-8 animate-in fade-in duration-200">
      
      {/* Header & Controls */}
      <div className="mb-8 w-full border-b border-border-subtle pb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-foreground tracking-tight mb-1 flex items-center gap-2">
            Context Inbox
          </h1>
          <p className="text-sm text-muted">
            Review and approve pending knowledge graph mutations generated by the Reflection Engine.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button 
            onClick={fetchInbox}
            className="p-2 text-muted hover:text-foreground bg-surface-1 border border-border-subtle hover:border-strong rounded-xl transition-all cursor-pointer"
            title="Refresh Inbox"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
          
          <div className="flex items-center gap-1.5 px-3 py-1.5 bg-surface-1 rounded-xl border border-border-subtle text-xs font-medium text-foreground">
            <AlertCircle className="w-4 h-4 text-warning" />
            <span>{nodes.length} Pending</span>
          </div>
        </div>
      </div>

      {/* Filter Tabs & Batch Actions Bar */}
      <div className="flex flex-col sm:flex-row justify-between items-center gap-4 mb-6">
        
        {/* Filter Pills */}
        <div className="flex items-center gap-1 bg-surface-1 p-1 rounded-xl border border-border-subtle text-xs w-full sm:w-auto">
          <button
            onClick={() => setActiveFilter("all")}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all cursor-pointer ${
              activeFilter === "all" ? "bg-surface-2 text-foreground shadow-sm" : "text-muted hover:text-foreground"
            }`}
          >
            All ({nodes.length})
          </button>
          <button
            onClick={() => setActiveFilter("high")}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all cursor-pointer ${
              activeFilter === "high" ? "bg-surface-2 text-foreground shadow-sm" : "text-muted hover:text-foreground"
            }`}
          >
            High Confidence ({nodes.filter(n => n.confidence >= 0.90).length})
          </button>
          <button
            onClick={() => setActiveFilter("review")}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all cursor-pointer ${
              activeFilter === "review" ? "bg-surface-2 text-foreground shadow-sm" : "text-muted hover:text-foreground"
            }`}
          >
            Needs Review ({nodes.filter(n => n.confidence < 0.90).length})
          </button>
        </div>

        {/* Batch Action Buttons */}
        {filteredNodes.length > 0 && (
          <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
            <button
              onClick={() => handleBatchAction("approve")}
              disabled={batching}
              className="px-3.5 py-1.5 bg-foreground text-background hover:opacity-90 font-medium text-xs rounded-xl flex items-center gap-1.5 transition-all disabled:opacity-50 cursor-pointer shadow-sm"
            >
              <Check className="w-3.5 h-3.5" />
              <span>Approve All ({filteredNodes.length})</span>
            </button>
            <button
              onClick={() => handleBatchAction("reject")}
              disabled={batching}
              className="px-3.5 py-1.5 bg-surface-1 hover:bg-surface-2 border border-border-subtle text-muted hover:text-foreground font-medium text-xs rounded-xl flex items-center gap-1.5 transition-all disabled:opacity-50 cursor-pointer"
            >
              <Trash2 className="w-3.5 h-3.5" />
              <span>Reject All</span>
            </button>
          </div>
        )}
      </div>

      {/* Content Stream */}
      {loading ? (
        <div className="space-y-4">
          <InboxItemSkeleton />
          <InboxItemSkeleton />
          <InboxItemSkeleton />
        </div>
      ) : filteredNodes.length === 0 ? (
        <div className="w-full flex flex-col items-center justify-center p-20 bg-surface-1/50 rounded-2xl border border-border-subtle border-dashed text-center animate-in fade-in duration-200">
          <div className="w-12 h-12 rounded-full bg-surface-2 border border-border-subtle flex items-center justify-center mb-4 text-foreground">
            <CheckCircle2 className="w-6 h-6 text-foreground" />
          </div>
          <h2 className="text-base font-semibold text-foreground mb-1">Inbox Zero</h2>
          <p className="text-xs text-muted max-w-sm leading-relaxed mb-6">
            All pending knowledge graph mutations have been reviewed. Your Context Engine graph is 100% up to date.
          </p>
          <button
            onClick={fetchInbox}
            className="px-4 py-2 bg-surface-2 border border-border-subtle hover:border-strong text-foreground text-xs font-medium rounded-xl transition-all cursor-pointer"
          >
            Check for New Events
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredNodes.map((node) => (
            <Card key={node.id} className="p-6 transition-all duration-200 hover:border-strong">
              <div className="flex flex-col md:flex-row gap-6 justify-between items-start">
                <div className="flex-1 space-y-3">
                  <div className="flex items-center gap-3">
                    <span className="px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider rounded-md bg-surface-2 text-foreground border border-border-subtle">
                      {node.type}
                    </span>
                    <h3 className="text-base font-semibold text-foreground tracking-tight">{node.title}</h3>
                  </div>
                  
                  <p className="text-xs text-muted leading-relaxed bg-surface-1/80 p-3.5 rounded-xl border border-border-subtle font-sans">
                    {node.summary}
                  </p>
                  
                  <div className="flex items-center gap-4 text-[11px] font-mono text-muted">
                    <span className="flex items-center gap-1">
                      <Zap className="w-3 h-3 text-primary" /> Confidence: {(node.confidence * 100).toFixed(0)}%
                    </span>
                    <span>•</span>
                    <span>{new Date(node.created_at).toLocaleString()}</span>
                  </div>
                </div>
                
                <div className="flex flex-row md:flex-col gap-2 shrink-0 w-full md:w-auto pt-2 md:pt-0 border-t md:border-t-0 border-border-subtle">
                  <button
                    onClick={() => handleAction(node.id, "approve")}
                    disabled={actionLoading === node.id}
                    className="flex-1 md:flex-initial px-4 py-2 bg-foreground text-background hover:opacity-90 font-medium text-xs rounded-xl flex items-center justify-center gap-1.5 transition-all disabled:opacity-50 cursor-pointer shadow-sm"
                  >
                    <Check className="w-3.5 h-3.5" />
                    <span>Approve</span>
                  </button>
                  <button
                    onClick={() => handleAction(node.id, "reject")}
                    disabled={actionLoading === node.id}
                    className="flex-1 md:flex-initial px-4 py-2 bg-surface-1 hover:bg-surface-2 border border-border-subtle text-muted hover:text-foreground font-medium text-xs rounded-xl flex items-center justify-center gap-1.5 transition-all disabled:opacity-50 cursor-pointer"
                  >
                    <XCircle className="w-3.5 h-3.5" />
                    <span>Reject</span>
                  </button>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
